version: '3.8'

services:
  frontend:
    image:
      - ${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    image:
      - ${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - RABBITMQ_BROKER=${RABBITMQ_BROKER}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - REDIS_DOMAIN=${REDIS_DOMAIN}
      - REDIS_PORT=${REDIS_PORT}
      - ACTIVEMQ_BROKER=${ACTIVEMQ_BROKER}
      - ACTIVEMQ_USER=${ACTIVEMQ_USER}
      - ACTIVEMQ_PASSWORD=${ACTIVEMQ_PASSWORD}
      - CLOUD_AWS_S3_BUCKET=${CLOUD_AWS_S3_BUCKET}
      - CLOUD_AWS_S3_DOMAIN=${CLOUD_AWS_S3_DOMAIN}
      - CLOUD_AWS_REGION_STATIC=${CLOUD_AWS_REGION_STATIC}
      - CLOUD_AWS_CREDENTIALS_ACCESSKEY=${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      - CLOUD_AWS_CREDENTIALS_SECRETKEY=${CLOUD_AWS_CREDENTIALS_SECRETKEY}
      - CLOUD_AWS_DYNAMODB_ACCESSKEY=${CLOUD_AWS_DYNAMODB_ACCESSKEY}
      - CLOUD_AWS_DYNAMODB_SECRETKEY=${CLOUD_AWS_DYNAMODB_SECRETKEY}
      - ACTIVEMQ_QNAME=${ACTIVEMQ_QNAME}
      - STOMP_HOST=${STOMP_HOST}

networks:
  my_network:
    driver: bridge