#cloud:
#  aws:
#    credentials:
#      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
#      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
#    s3:
#      bucket: itsmineBucket
#    region:
#      static: ${CLOUD_AWS_REGION_STATIC}
#    stack:
#      auto: false

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      domain: ${CLOUD_AWS_S3_DOMAIN}
    stack.auto: false
    region.static: ${CLOUD_AWS_REGION_STATIC}
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
dynamodb:
  table:
    name: Messages
  credentials:
    accessKey: ${CLOUD_AWS_DYNAMODB_ACCESSKEY}
    secretKey: ${CLOUD_AWS_DYNAMODB_SECRETKEY}